/**
 * OFFLINE generator for the Quran structural boundary data.
 *
 * Run manually (NOT at build/runtime); its output under src/lib/quran/data/*.ts
 * is committed so the app and CI have zero network/DB dependency:
 *
 *     npx tsx scripts/generate-quran-data.ts
 *
 * ── Source ────────────────────────────────────────────────────────────────
 * Tanzil.net `quran-data.xml` — the canonical machine-readable Quran metadata.
 * Its boundary markers are already ayah-aligned (each points at a whole ayah):
 *   <pages>   604 × <page   index sura aya/>   -> page starts
 *   <juzs>     30 × <juz    index sura aya/>   -> juz starts
 *   <hizbs>   240 × <quarter index sura aya/>  -> rub-al-hizb (quarter) starts;
 *                                                 hizb = every 2 quarters? NO:
 *                                                 each quarter IS a rub; 4 rubs
 *                                                 per hizb, 8 per juz. So:
 *                                                 hizb N starts at quarter 4N-3,
 *                                                 juz  N starts at quarter 8N-7.
 *
 * ── Half-page segments (⚠ derived & opinionated, NOT canonical) ─────────────
 * No public dataset defines a "half page that ends on a whole ayah": physically
 * a half page is 7.5 of 15 lines and the mushaf splits ayahs across lines. For
 * the MVP (ayah-boundary precision) we approximate: within each page's ayah span
 * [start..end], the first half ends at the ayah nearest the ayah-count midpoint,
 * the second half runs to the page's last ayah. This is documented as approximate
 * in the plan; to make it precise later, replace deriveHalfPageSplit() with a
 * QUL 15-line Madani layout lookup (first half = ayahs starting on line <= 7).
 *
 * Everything is expressed as 1-based GLOBAL ayah indices (1..6236) so the runtime
 * helpers in src/lib/quran/structure.ts can binary-search them directly.
 */

import { writeFileSync, mkdirSync } from "node:fs"
import { join } from "node:path"
import { SURAHS } from "../src/lib/quran/surahs"

const TANZIL_URL = "https://tanzil.net/res/text/metadata/quran-data.xml"
const OUT_DIR = join(process.cwd(), "src", "lib", "quran", "data")

// ── surah <-> global (self-contained, mirrors structure.ts) ─────────────────
const OFFSET: number[] = new Array(SURAHS.length + 1).fill(0)
{
  let running = 0
  for (const s of SURAHS) {
    OFFSET[s.number] = running
    running += s.ayahCount
  }
}
const TOTAL = SURAHS.reduce((n, s) => n + s.ayahCount, 0)
function toGlobal(sura: number, aya: number): number {
  return OFFSET[sura] + aya
}

// ── parse a flat list of <tag index sura aya/> markers into global indices ───
function parseMarkers(xml: string, tag: string): number[] {
  const re = new RegExp(`<${tag}\\b[^>]*\\bsura="(\\d+)"[^>]*\\baya="(\\d+)"[^>]*/>`, "g")
  const byIndex: number[] = []
  const idxRe = /\bindex="(\d+)"/
  let m: RegExpExecArray | null
  while ((m = re.exec(xml)) !== null) {
    const whole = m[0]
    const idxM = idxRe.exec(whole)
    if (!idxM) continue
    const index = Number(idxM[1])
    byIndex[index] = toGlobal(Number(m[1]), Number(m[2]))
  }
  // Drop the unused index-0 slot; return dense 0-based array in marker order.
  return byIndex.slice(1)
}

/** first-half end (global index) for a page spanning [startG, endG] inclusive. */
function deriveHalfPageSplit(startG: number, endG: number): number {
  const ayahs = endG - startG + 1
  if (ayahs <= 1) return startG // single-ayah page: no real split
  // midpoint by ayah count, first half at least 1 ayah, at most all-but-one.
  const half = Math.max(1, Math.min(ayahs - 1, Math.round(ayahs / 2)))
  return startG + half - 1
}

function emit(name: string, literal: string, banner: string): void {
  const body = `// GENERATED by scripts/generate-quran-data.ts — DO NOT EDIT BY HAND.\n// ${banner}\n\n${literal}\n`
  writeFileSync(join(OUT_DIR, name), body, "utf8")
  // eslint-disable-next-line no-console
  console.log(`wrote ${name}`)
}

async function main(): Promise<void> {
  // eslint-disable-next-line no-console
  console.log(`fetching ${TANZIL_URL} …`)
  const res = await fetch(TANZIL_URL)
  if (!res.ok) throw new Error(`Tanzil fetch failed: ${res.status}`)
  const xml = await res.text()

  const pageStarts = parseMarkers(xml, "page") // 604
  const juzStarts = parseMarkers(xml, "juz") // 30
  const quarterStarts = parseMarkers(xml, "quarter") // 240 (rub-al-hizb)

  if (pageStarts.length !== 604) throw new Error(`expected 604 pages, got ${pageStarts.length}`)
  if (juzStarts.length !== 30) throw new Error(`expected 30 juz, got ${juzStarts.length}`)
  if (quarterStarts.length !== 240) throw new Error(`expected 240 quarters, got ${quarterStarts.length}`)

  // Half-page segments in reading order: for each page, [firstHalf, secondHalf].
  const segments: Array<{ s: number; e: number }> = []
  for (let p = 0; p < pageStarts.length; p++) {
    const startG = pageStarts[p]
    const endG = (p + 1 < pageStarts.length ? pageStarts[p + 1] - 1 : TOTAL)
    const mid = deriveHalfPageSplit(startG, endG)
    segments.push({ s: startG, e: mid })
    // Second half only when the page actually splits. A single-ayah page (e.g.
    // 2:282, the debt ayah, which fills a whole mushaf page) yields ONE segment;
    // pushing a duplicate here would break segment contiguity.
    if (mid < endG) segments.push({ s: mid + 1, e: endG })
  }

  mkdirSync(OUT_DIR, { recursive: true })
  emit(
    "page-starts.ts",
    `export const PAGE_STARTS: number[] = ${JSON.stringify(pageStarts)}`,
    "Global ayah index of the first ayah of each of the 604 Madani pages.",
  )
  emit(
    "quarter-starts.ts",
    `export const QUARTER_STARTS: number[] = ${JSON.stringify(quarterStarts)}`,
    "Global ayah index of each of the 240 rub-al-hizb (quarter) starts. hizb=4 quarters, juz=8.",
  )
  emit(
    "juz-starts.ts",
    `export const JUZ_STARTS: number[] = ${JSON.stringify(juzStarts)}`,
    "Global ayah index of the first ayah of each of the 30 juz.",
  )
  emit(
    "segments.ts",
    `export const HALF_PAGE_SEGMENTS: { s: number; e: number }[] = ${JSON.stringify(segments)}`,
    "APPROXIMATE ayah-aligned half-page segments (see generator header). {s,e} = global start/end.",
  )
  // eslint-disable-next-line no-console
  console.log(`done: ${segments.length} half-page segments, TOTAL=${TOTAL}`)
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err)
  process.exit(1)
})
