// GENERATED by scripts/generate-quran-data.ts — DO NOT EDIT BY HAND.
// Global ayah index of the first ayah of each of the 30 juz.

export const JUZ_STARTS: number[] = [1,149,260,386,517,641,751,900,1042,1201,1328,1479,1649,1803,2030,2215,2484,2674,2876,3215,3386,3564,3733,4090,4265,4511,4706,5105,5242,5673]
